// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkdVi1b1yMrTqxEVj3ik87DTZYlS11ARY',
    appId: '1:975467059933:web:8919b58893ed0961825934',
    messagingSenderId: '975467059933',
    projectId: 'ogma-de793',
    authDomain: 'ogma-de793.firebaseapp.com',
    storageBucket: 'ogma-de793.appspot.com',
    measurementId: 'G-PJQR77WB79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqlv0iHSIUy1BE3UleirXOSx1n8PSoYOs',
    appId: '1:975467059933:android:194e1b31e184d613825934',
    messagingSenderId: '975467059933',
    projectId: 'ogma-de793',
    storageBucket: 'ogma-de793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1AJBa7HhRk0CrlS_jfPfS0FkjFWYZcMk',
    appId: '1:975467059933:ios:bf8b7292686b7580825934',
    messagingSenderId: '975467059933',
    projectId: 'ogma-de793',
    storageBucket: 'ogma-de793.appspot.com',
    iosClientId: '975467059933-gm2jdh7rbg4j88og8lvt3av1119tuu8k.apps.googleusercontent.com',
    iosBundleId: 'com.ogmaproject.ogma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1AJBa7HhRk0CrlS_jfPfS0FkjFWYZcMk',
    appId: '1:975467059933:ios:bf8b7292686b7580825934',
    messagingSenderId: '975467059933',
    projectId: 'ogma-de793',
    storageBucket: 'ogma-de793.appspot.com',
    iosClientId: '975467059933-gm2jdh7rbg4j88og8lvt3av1119tuu8k.apps.googleusercontent.com',
    iosBundleId: 'com.ogmaproject.ogma',
  );
}
